### ISSUE TITLE
Code for HTML

### ISSUE THREAD

**Issue by AbeerGandhi** [Group6-Mini-project-DAAM/Tile-Matching-Game#2]

**Comment by MrityunjayGupta1** [comment]
I have completed my HTML code. Please check and verify.

**Comment by AbeerGandhi** [comment]
Yes it is working!
No need to change the code.

**Comment by MrityunjayGupta1** [comment]
Code edited. I've made some changes, just have a look

**Comment by AbeerGandhi** [comment]
Okay.
