### ISSUE TITLE
Code for JavaScript

### ISSUE THREAD

**Issue by AbeerGandhi** [Group6-Mini-project-DAAM/Tile-Matching-Game#4]

**Comment by MrityunjayGupta1** [comment]
I've completed my code for HTML in the codespaces and want you to check the code and tell me if there is any error.

**Comment by AbeerGandhi** [comment]
The code is working properly.
You dont need to add anything.

**Comment by AmanPatne** [comment]
I have completed my Javascript code .Pls check and verify

**Comment by AbeerGandhi** [comment]
Code is working properly.
No need to change.
